[workspace]
resolver = "2"
members = [
    "flow",
    "r01-diffusion",
    "r02-driven",
    "r03-advection",
    "r04-grayscott",
    "r05-convection",
    "r06-swift-hohenberg",
    "r07-excitable",
    "r08-cahn-hilliard",
    "server",
    "flow-wasm",
]

[workspace.package]
edition = "2021"
license = "MIT"
authors = ["Anton Bursch"]
repository = "https://github.com/AntonBursch/life"

[profile.release]
lto = true
codegen-units = 1
